Add Domain layer
albertoh8/RssAggregator pull request #6
Opened 2022-11-15 19:14 UTC by albertoh8

## Descripción de la tarea

Crear una capa de dominio para definir la estructura de los datos con un caso de uso que guarda la información

## ¿Cómo se ha implementado?

Se añade un modelo que será la clase de datos en la cual asignamos que tipo de datos lo compondrán, se crea el repositorio que es una interfaz que tendrá una función para guardar los datos obtenidos y un caso de uso para guardar los datos llamando al repositorio

## Keywords

data class, repository, model, domain

## Screenshots or Video

## Objetivos

## Disclaimer

## Criterios de Evaluación

2022-11-15 19:37 UTC, alvarogo1998 approved these changes
La PR esta bien pero mira los comentarios

2022-11-15 19:37 UTC, alvarogo1998 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/Repositories.kt
> +    fun create(name: String, url: String): Rss
podrias tratar Rss? como si fuera null

2022-11-15 19:37 UTC, alvarogo1998 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/SaveRssUseCase.kt
> +    fun execute(name: String, url: String): Rss {
Si lo cambias en la anterior aquí también tendrías que modificarla

2022-11-16 14:40 UTC, albertoh8 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/Repositories.kt
> +    fun create(name: String, url: String): Rss
Lo he dejado asi por que al ser solo dos atributos he pensado que sera muy dificil que sea null

2022-11-16 14:45 UTC, albertoh8 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/SaveRssUseCase.kt
> +    fun execute(name: String, url: String): Rss {
Al ser solo dos atributos he pensado que no recibiría nulos

2022-11-17 08:15 UTC, josem-perram commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/Repositories.kt
> +    fun create(name: String, url: String): Rss
Por qué devuelves un RSS ??

2022-11-17 08:17 UTC, josem-perram requested changes
Por favor, revisa y argumenta los comentarios. Gracias.

2022-11-17 12:20 UTC, albertoh8 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/Repositories.kt
> +    fun create(name: String, url: String): Rss
Lo hice rápido y me confundí con la función execute de el caso de uso, ya esta arreglado

2022-11-17 15:09 UTC, alvarogo1998 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/Repositories.kt
> +    fun create(rss: Rss)
Creo q seria mejor meter los 2 atributos, ya que aquí estarías limitado a los datos al del Rss, también podría create tener un nombre mas descriptivo como por ej: createRss

2022-11-17 15:11 UTC, alvarogo1998 approved these changes
Esta bien, pero mira los comentarios.

2022-11-22 19:33 UTC, albertoh8 commented on app/src/main/java/com/albertoherjim/rssaggregator/domain/Repositories.kt
> +    fun create(rss: Rss)
Pero rss es el modelo que ya tiene los 2 atributos

2022-11-27 22:48 UTC, josem-perram approved these changes
Por favor, revisa lo que se comenta en el ticket a la hora de pasar los parámetros.

2022-11-27 22:50 UTC, josem-perram requested changes
Please, lee bien el ticket ahí te indica lo de los parámetros.

2022-12-16 15:09 UTC, josem-perram approved these changes
🚀

2022-12-16 15:11 UTC, merged